/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Container, Engine, ISourceOptions } from "tsparticles-engine";
export { Container, Engine, ISourceOptions } from "tsparticles-engine";
export namespace Components {
    interface StencilParticles {
        /**
          * The id
         */
        "id": string;
        "options": ISourceOptions;
        "particlesInit": (engine: Engine) => Promise<void>;
        "particlesLoaded": (container: Container) => Promise<void>;
        "url": string;
    }
}
declare global {
    interface HTMLStencilParticlesElement extends Components.StencilParticles, HTMLStencilElement {
    }
    var HTMLStencilParticlesElement: {
        prototype: HTMLStencilParticlesElement;
        new (): HTMLStencilParticlesElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-particles": HTMLStencilParticlesElement;
    }
}
declare namespace LocalJSX {
    interface StencilParticles {
        /**
          * The id
         */
        "id"?: string;
        "options"?: ISourceOptions;
        "particlesInit"?: (engine: Engine) => Promise<void>;
        "particlesLoaded"?: (container: Container) => Promise<void>;
        "url"?: string;
    }
    interface IntrinsicElements {
        "stencil-particles": StencilParticles;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-particles": LocalJSX.StencilParticles & JSXBase.HTMLAttributes<HTMLStencilParticlesElement>;
        }
    }
}
